#!/bin/bash
# auto-generated by Artisan on 2022-06-01 15:52:30.100311 +0000 UTC

# configure 'interlink' database release information
dbman config use -n ilink-config
dbman config set repo.uri https://raw.githubusercontent.com/southwinds-io/interlink-db/master
dbman config set db.provider _pgsql
dbman config set db.host db
dbman config set db.port 5432
dbman config set db.name interlink
dbman config set db.username ${ILINK_APP_DB_USER}
dbman config set db.password ${ILINK_APP_DB_PWD}
dbman config set db.adminusername postgres
dbman config set db.adminpassword ${DB_POSTGRES_PASSWORD}
dbman config set appversion 0.0.4

# create 'ilink' database
dbman db create

# deploy 'ilink' database schema
dbman db deploy

